# Generated by Django 5.0.4 on 2024-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=20)),
                ('photo', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
